import 'dart:math';

import 'package:flutter/material.dart';

class Utils {
  static final random = Random();

  static const randomNames = [
    'James Lumpkin',
    'Malika Fields',
    'Avery Burney',
    'Deante Weis',
    'Darrian McCollum',
    'Braxton Ware',
    'Symone Means',
    'Kianna Willis',
    'Alli Burr',
    'Kathleen Yoo',
    'Gunner Garay',
    'Eva Luong',
    'Alicia Cheung',
    'Weston Rider',
    'Demonte Irby',
    'Jayden Crist',
    'Bridger Sharp',
    'Quinten Karr',
    'Stephanie Francisco',
    'Dandre Vieira',
    'Susannah Knoll',
    'Emmett Fagan',
    'Malik Fletcher',
    'Walter Fennell',
    'Ayleen Thacker',
    'Tony Valentin',
    'Amya Cummings',
    'Jase Parra',
    'Alberto Lorenzo',
    'Martin Hofer',
    'Joy Logsdon',
    'Carson Robison',
    'Obed Locklear',
    'Cheyenne Frazier',
    'Adonis Crews',
    'Mauricio Craig',
    'Obed Mondragon',
    'Denis Durbin',
    'Lucy Chacon',
    'Karson Cheatham',
    'Richard Terry',
    'Noah Bustamante',
    'Karime Antonio',
    'Milo Humphrey',
    'Dorian Clapp',
    'Gissel Gagne',
    'Christian Maciel',
    'Ronaldo Halstead',
    'Tatianna Coyne',
    'Bridgett Moua',
    'Hailie Oswald',
    'Jeff Sheppard',
    'Shakira Bagwell',
    'Connor Smalley',
    'Jaxon Lawless',
    'Zahra Copeland',
    'Ronald Ludwig',
    'Amberly Turk',
    'Koby Brinson',
    'Christie Berg',
    'Tristen Padron',
    'Sofia Kerr',
    'Marin Salisbury',
    'Natalia Connor',
    'Rhea Rosales',
    'Marshall Wertz',
    'Jelani Holliday',
    'Greyson Sample',
    'Dakotah Peacock',
    'Braydon Pressley',
    'Darrin Sands',
    'Nico Adler',
    'Carla Crowell',
    'Connor Seibert',
    'Beyonce Bowling',
    'Erykah Mabry',
    'Yesica Sutherland',
    'Delaney Morse',
    'Mykala Sheffield',
    'Jayvon Collins',
    'Yosef Leavitt',
    'Cailin Wharton',
    'Michaela Cody',
    'Lena McWilliams',
    'Lawson Casteel',
    'Kelsi Harder',
    'Khalid Brandon',
    'Ayden Caballero',
    'Zariah Hostetler',
    'Brandy Toney',
    'Jair Coffin',
    'Luna Williamson',
    'Austen Goff',
    'Raegan Christenson',
    'Ian Brewster',
    'Piper Kirkpatrick',
    'Candice Villasenor',
    'Jerod Ogden',
    'Berenice Beavers',
    'Junior Richards',
  ];

  static bool isColorDark(Color color) {
    return ThemeData.estimateBrightnessForColor(color) == Brightness.dark;
  }

  static int randomInt() {
    return random.nextInt(pow(2, 31).toInt());
  }

  static String randomName() {
    return randomNames[random.nextInt(randomNames.length)];
  }
}
